# Generated by Django 4.2.5 on 2023-09-20 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='access',
        ),
        migrations.AddField(
            model_name='productaccess',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.product'),
            preserve_default=False,
        ),
    ]
