# Generated by Django 4.2.5 on 2023-09-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_lesson_products_product_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonview',
            name='last_time_viewed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
